### PR TITLE
(Re-)Introduce InvalidWatcherException

### LINKED ISSUE #58: Operations on Invalid Watchers Must Throw
From #53:

> May we please add that cancel()'ling multiple times or any other operation on already invalid watchers is disallowed (as watcher ids may be reused)?
> Calling unreference(), reference(), enable() and disable() multiple times must not error.

Is everyone okay with that (I'll open a PR tomorrow to add that in docblocks)? Or are there issues here?

### PR DESCRIPTION
**Pull request by bwoebi**
Fixes #58.

Followup to #69 with the following rules:

Any operation must happen on a valid watcher, except cancel(), which does not check watcher validity (and just silently returns).

### CODE REVIEW

File: src/Loop/Driver.php [hunk 1]
```diff
@@ -114,11 +116,13 @@ public function enable($watcherId);
...
      *
      * @return void
+     *
+     * @throws InvalidWatcherException Thrown if the watcher identifier is invalid.
      */
     public function disable($watcherId);
 
     /**
-     * Cancel a watcher.
+     * Cancel a watcher. This marks the watcher as invalidated. Calling this function MUST never fail, even when passed an invalid watcher.
```
Comment (kelunik) [inline src/Loop/Driver.php]: `invalidated` → `invalid` to be consistent.

File: src/Loop/InvalidWatcherException.php [hunk 2]
```diff
@@ -0,0 +1,12 @@
+<?php
+
+namespace Interop\Async\Loop;
+
+/**
+ * MUST NOT be thrown by cancel().
```
Comment (kelunik) [inline src/Loop/InvalidWatcherException.php]: That shouldn't be mentioned here.

**Comment by bwoebi** [comment]
May everyone please add a :+1: or add a comment with his problems so that we can eventually merge it if there are no complaints.

**Comment by AndrewCarterUK** [comment]
Might be worth being explicit that cancel should not throw an exception when given an invalid watcher if this is the route we are going down.

**Comment by bwoebi** [comment]
It's present on the Driver::cancel docs:

> - Cancel a watcher. This marks the watcher as invalid. Calling this function MUST never fail, even when passed an invalid watcher.

It already has no @throws annotation, that should be good enough for Loop::cancel() docs.
